-- Script Date: 2020/03/09 23:08  - ErikEJ.SqlCeScripting version 3.5.2.85
DROP TABLE [CHARACTERS];

CREATE TABLE [CHARACTERS] (
  [ID] INTEGER PRIMARY KEY AUTOINCREMENT
, [CHARACTER_NAME] TEXT NOT NULL
, KANA TEXT
, [BIRTHDAY] TEXT
, [PROBABLE_AGE] INTEGER
, [ORGANIZATION] INTEGER NOT NULL
, [ZANPAKUTOU] INTEGER NULL
);
