-- Script Date: 2019/11/27 16:20  - ErikEJ.SqlCeScripting version 3.5.2.81
DROP TABLE IMAGE_SOURCES
;

-- Script Date: 2019/12/25 18:49  - ErikEJ.SqlCeScripting version 3.5.2.85
CREATE TABLE [IMAGE_SOURCES] (
  [ZIP_SETTINGS_ID] INTEGER NOT NULL
, [IMAGE_SOURCE_PATH] TEXT NOT NULL
, [SOURCE_KIND] INTEGER NOT NULL
, [LIST_ORDER] INTEGER NOT NULL
, CONSTRAINT [PK_IMAGE_SOURCES] PRIMARY KEY ([ZIP_SETTINGS_ID],[IMAGE_SOURCE_PATH])
);
