-- Script Date: 2019/11/27 16:20  - ErikEJ.SqlCeScripting version 3.5.2.81
DROP TABLE ZIP_FILE_SETTINGS
;

CREATE TABLE [ZIP_FILE_SETTINGS] (
  [ID] INTEGER PRIMARY KEY AUTOINCREMENT
, [EXTRACT_FOLDER] TEXT NOT NULL
, FOLDER_NAME_SEQ INTEGER
, FOLDER_NAME_TEMPLATE TEXT
, FILE_NAME_TEMPLATE TEXT
, [INSERT_DATE] TEXT NOT NULL
);