-- Script Date: 2019/11/27 16:20  - ErikEJ.SqlCeScripting version 3.5.2.81
CREATE TABLE [ZIP_FILE_SETTINGS] (
  [ID] INTEGER PRIMARY KEY AUTOINCREMENT
, [EXTRACT_FOLDER] TEXT NOT NULL
, [INSERT_DATE] TEXT NOT NULL
);